import os
import json
import asyncio
from langchain_core.messages import HumanMessage
from src.workflow.builder import sql_chatbot_graph
from src.core.config import settings
from src.utils.logger import logger

async def run_test(query, level_name):
    print(f"\n--- Testing Level: {level_name} ---")
    print(f"Query: {query}")
    
    config = {
        "configurable": {
            "thread_id": f"test_{level_name}",
            "user_id": "test_user"
        }
    }
    
    input_data = {
        "messages": [HumanMessage(content=query)],
        "user_id": "test_user"
    }
    
    results = {
        "level": level_name,
        "query": query,
        "response": "",
        "logs": []
    }
    
    try:
        # Invoke the graph
        response = sql_chatbot_graph.invoke(input_data, config=config)
        
        # Capture final answer
        final_msg = response["messages"][-1].content
        results["response"] = final_msg
        
        # Capture agent logs for thought process analysis
        results["logs"] = response.get("agent_logs", [])
        
        print(f"Response: {final_msg[:100]}...")
        return results
    except Exception as e:
        print(f"Error: {e}")
        results["error"] = str(e)
        return results

async def main():
    test_suite = [
        ("List the top 10 most expensive films to rent, including their titles and rental rates.", "Level 1: Happy Path"),
        ("Which customers have rented the most Action films? Provide their full names and the total count.", "Level 2: Bridge/Complexity"),
        ("Show me the total rental revenue generated by 'Mary Smith'.", "Level 3: Ambiguity Trap")
    ]
    
    all_results = []
    for query, level in test_suite:
        res = await run_test(query, level)
        all_results.append(res)
    
    # Write report to .txt file
    report_path = "agent_performance_report.txt"
    with open(report_path, "w") as f:
        f.write("AGENT PERFORMANCE REPORT\n")
        f.write("========================\n\n")
        for res in all_results:
            f.write(f"LEVEL: {res['level']}\n")
            f.write(f"USER QUERY: {res['query']}\n")
            f.write(f"AGENT RESPONSE:\n{res['response']}\n")
            f.write("-" * 20 + "\n")
            f.write("THOUGHT PROCESS LOGS:\n")
            for log in res['logs']:
                f.write(f"Node: {log.get('node_name', 'unknown')}\n")
                f.write(f"Thought: {log.get('thought_process', 'N/A')}\n")
            f.write("\n" + "="*40 + "\n\n")
            
    print(f"\nReport generated: {report_path}")

if __name__ == "__main__":
    asyncio.run(main())
