from typing import List, Optional

from pydantic import BaseModel, Field, ConfigDict

from src.workflow.schema.base import BaseNodeOutput


class SubTask(BaseModel):
    """
    An atomic unit of work for a Worker node.
    """
    model_config = ConfigDict(extra="forbid")
    task_id: str = Field(..., description="Unique ID for the sub-task (e.g., 'task_1').")
    description: str = Field(..., description="Description of what this sub-task generates.")
    tables: List[str] = Field(..., description="Tables involved in this specific snippet.")
    required_columns: List[str] = Field(..., description="Columns that MUST be in the SELECT list for joins.")
    dependencies: List[str] = Field(..., description="IDs of tasks this task depends on.")

class JoinStep(BaseModel):
    """
    A single join operation between two sub-task snippets.
    """
    model_config = ConfigDict(extra="forbid")
    left: str = Field(..., description="Task ID of the left side (or 'base').")
    right: str = Field(..., description="Task ID of the right side snippet.")
    on: str = Field(..., description="The column name to join on (assumed same in both).")
    join_type: str = Field(..., description="inner, left, or cross.")

class JoinPlan(BaseModel):
    """
    The blueprint for assembling multiple SQL snippets.
    """
    model_config = ConfigDict(extra="forbid")
    base_task: str = Field(..., description="The ID of the primary task to start the FROM clause.")
    steps: List[JoinStep] = Field(..., description="Ordered steps to join additional snippets.")
    final_select: str = Field(..., description="The final columns to select (comma-separated list of 'alias.column').")
    where: Optional[str] = Field(None, description="Optional final WHERE clause (e.g. 't1.amount > 10').")
    order_by: Optional[str] = Field(None, description="Optional final ORDER BY clause (e.g. 't1.total DESC').")
    limit: Optional[int] = Field(None, description="Optional final LIMIT count.")

class DecomposerOutput(BaseNodeOutput):
    """
    The structured plan generated by the Manager for Divide and Conquer.
    """
    sub_tasks: List[SubTask] = Field(..., description="List of atomic SQL generation tasks.")
    join_plan: JoinPlan = Field(..., description="Deterministic blueprint for the SQLTranspiler.")
    complexity_score: int = Field(..., ge=1, le=10, description="Estimated complexity (1-10).")

class WorkerOutput(BaseNodeOutput):
    """
    The structured result from a ReliableWorker.
    """
    sql: str = Field(..., description="The generated SQL snippet.")
