from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field

class BaseNodeOutput(BaseModel):
    """
    Base class for all node outputs to ensure deterministic observability.
    """
    node_name: str = Field(..., description="Name of the node that produced this output.")
    thought_process: str = Field(..., description="A strictly concise summary of your reasoning (max 20 words).")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Execution metadata (latency, tokens, etc.)")

class GuardianOutput(BaseNodeOutput):
    """
    Structured output for the Guardian node.
    """
    intent: str = Field(..., description="The categorized intent: SQL, DENY, or CLARIFY.")

class ClassifierOutput(BaseNodeOutput):
    """
    Structured output for the SQL Complexity Classifier.
    """
    is_complex: bool = Field(..., description="True if the query requires joins, complex logic, or multi-table lookups.")

class SchemaSelectorOutput(BaseNodeOutput):
    """
    Structured output for the Hybrid Schema Selector.
    """
    selected_tables: List[str] = Field(default_factory=list, description="Tables identified as relevant.")
    selected_columns: Dict[str, List[str]] = Field(default_factory=dict, description="Mapping of table names to relevant columns.")
    fk_relationships: List[Dict[str, str]] = Field(default_factory=list, description="Explicit foreign key connections between selected tables.")
    fk_path_identified: str = Field("", description="Natural language description of the identified join path.")

class AnchorSelection(BaseModel):
    """
    Structured internal output for identifying anchor tables.
    """
    anchors: List[str] = Field(..., description="List of the 2-3 most relevant anchor tables.")
    thought_process: str = Field("", description="Internal reasoning for selection.")

class ClarificationOutput(BaseModel):
    """
    Structured output for generating clarification questions.
    """
    clarification_question: str = Field(..., description="The concise follow-up question for the user.")

class SQLGenerationOutput(BaseModel):
    """
    Structured output for generating or healing SQL.
    """
    sql: str = Field(..., description="The generated or corrected SQL query.")

class ExecuteSQLOutput(BaseModel):
    """
    Structured internal result for SQL execution (non-LLM).
    """
    status: str
    data: List[Dict[str, Any]] = Field(default_factory=list)
    row_count: int = 0
    is_aggregated: bool = False
    error_message: Optional[str] = None

class SubTask(BaseModel):
    """
    An atomic unit of work for a Worker node.
    """
    task_id: str = Field(..., description="Unique ID for the sub-task (e.g., 'task_1').")
    description: str = Field(..., description="Description of what this sub-task generates.")
    tables: List[str] = Field(..., description="Tables involved in this specific snippet.")
    dependencies: List[str] = Field(default_factory=list, description="IDs of tasks this task depends on.")

class ManagerOutput(BaseNodeOutput):
    """
    The structured plan generated by the Manager for Divide and Conquer.
    """
    sub_tasks: List[SubTask] = Field(..., description="List of atomic SQL generation tasks.")
    join_plan: str = Field(..., description="Detailed instructions on how to join the resulting snippets.")
    complexity_score: int = Field(..., ge=1, le=10, description="Estimated complexity of the query.")

class ChatbotResponse(BaseNodeOutput):
    """
    Structured response for the general chatbot node.
    """
    response: str = Field(..., description="The natural language response from the chatbot.")

class SQLExample(BaseModel):
    """Deep structure for code comparisons."""
    original_error: str = Field(..., description="The exact SQL query that failed.")
    fixed_sql: str = Field(..., description="The corrected, working SQL query.")

class LessonBody(BaseModel):
    """The core content of the Staff Engineer lesson."""
    instruction: str = Field(..., description="The single, actionable rule for future agents.")
    mistake: str = Field(..., description="A clear description of the specific error made.")
    reasoning: str = Field(..., description="Markdown Root Cause Analysis and Future Proofing.")
    example: SQLExample = Field(..., description="SQL Query Comparison example.")

class LessonDistillationOutput(BaseNodeOutput):
    """
    Structured output for the Lesson Distiller (Self-Healing).
    """
    is_global: bool = Field(..., description="True if the lesson applies to all queries, False if table-specific.")
    tags: List[str] = Field(default_factory=list, description="Tags for the schema specific lessons.")
    title: str = Field(..., description="Short, descriptive title for the lesson.")
    body: LessonBody = Field(..., description="The core content of the lesson.")
    ending_note: str = Field(..., description="Professional sign-off (By following this instruction...)")

class SQLResponse(BaseModel):
    """
    Structured response from the LLM for SQL queries.
    """
    summary: Optional[str] = Field(
        default=None, 
        description="A natural language explanation or context-aware answer."
    )
