from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field, ConfigDict, AliasChoices

class BaseNodeOutput(BaseModel):
    """
    Base class for all node outputs to ensure deterministic observability.
    """
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    node_name: str = "unknown"
    thought_process: str = Field(
        ..., 
        validation_alias=AliasChoices("thought_process", "reason", "explanation"),
        description="A strictly concise summary of your reasoning (max 20 words)."
    )

class GuardianOutput(BaseNodeOutput):
    """
    Structured output for the Guardian node.
    """
    intent: str = Field(..., description="The categorized intent: SQL, DENY, or CLARIFY.")

class ClassifierOutput(BaseNodeOutput):
    """
    Structured output for the SQL Complexity Classifier.
    """
    is_complex: bool = Field(..., description="True if the query requires joins, complex logic, or multi-table lookups.")

class ColumnSelection(BaseModel):
    """Mapping of table names to relevant columns."""
    model_config = ConfigDict(extra="forbid")
    table_name: str = Field(..., description="Physical table name.")
    columns: List[str] = Field(..., description="List of column names.")

class FKRelationship(BaseModel):
    """Explicit foreign key connection."""
    model_config = ConfigDict(extra="forbid")
    source_table: str = Field(..., description="Source table.")
    source_column: str = Field(..., description="Source column.")
    target_table: str = Field(..., description="Target table.")
    target_column: str = Field(..., description="Target column.")

class SchemaSelectorOutput(BaseNodeOutput):
    """
    Structured output for the Hybrid Schema Selector.
    """
    selected_tables: List[str] = Field(..., description="Tables identified as relevant.")
    selected_columns: List[ColumnSelection] = Field(..., description="List of table column mappings.")
    fk_relationships: List[FKRelationship] = Field(..., description="Explicit foreign key connections.")
    fk_path_identified: str = Field(..., description="Natural language description of the identified join path.")

class AnchorSelection(BaseModel):
    """
    Structured internal output for identifying anchor tables.
    """
    model_config = ConfigDict(extra="forbid")
    anchors: List[str] = Field(..., description="List of the 2-3 most relevant anchor tables.")
    thought_process: str = Field(..., description="Internal reasoning for selection.")

class ClarificationOutput(BaseModel):
    """
    Structured output for generating clarification questions.
    """
    model_config = ConfigDict(extra="forbid")
    clarification_question: str = Field(..., description="The concise follow-up question for the user.")

class SQLGenerationOutput(BaseModel):
    """
    Structured output for generating or healing SQL.
    """
    model_config = ConfigDict(extra="forbid")
    sql: str = Field(..., description="The generated or corrected SQL query.")

class SubTask(BaseModel):
    """
    An atomic unit of work for a Worker node.
    """
    model_config = ConfigDict(extra="forbid")
    task_id: str = Field(..., description="Unique ID for the sub-task (e.g., 'task_1').")
    description: str = Field(..., description="Description of what this sub-task generates.")
    tables: List[str] = Field(..., description="Tables involved in this specific snippet.")
    required_columns: List[str] = Field(..., description="Columns that MUST be in the SELECT list for joins.")
    dependencies: List[str] = Field(..., description="IDs of tasks this task depends on.")

class JoinStep(BaseModel):
    """
    A single join operation between two sub-task snippets.
    """
    model_config = ConfigDict(extra="forbid")
    left: str = Field(..., description="Task ID of the left side (or 'base').")
    right: str = Field(..., description="Task ID of the right side snippet.")
    on: str = Field(..., description="The column name to join on (assumed same in both).")
    join_type: str = Field(..., description="inner, left, or cross.")

class JoinPlan(BaseModel):
    """
    The blueprint for assembling multiple SQL snippets.
    """
    model_config = ConfigDict(extra="forbid")
    base_task: str = Field(..., description="The ID of the primary task to start the FROM clause.")
    steps: List[JoinStep] = Field(..., description="Ordered steps to join additional snippets.")
    final_select: str = Field(..., description="The final columns to select from the joined set.")

class DecomposerOutput(BaseNodeOutput):
    """
    The structured plan generated by the Manager for Divide and Conquer.
    """
    sub_tasks: List[SubTask] = Field(..., description="List of atomic SQL generation tasks.")
    join_plan: JoinPlan = Field(..., description="Deterministic blueprint for the SQLTranspiler.")
    complexity_score: int = Field(..., ge=1, le=10, description="Estimated complexity (1-10).")

class WorkerOutput(BaseNodeOutput):
    """
    The structured result from a ReliableWorker.
    """
    sql: str = Field(..., description="The generated SQL snippet.")

class ChatbotResponse(BaseNodeOutput):
    """
    Structured response for the general chatbot node.
    """
    response: str = Field(..., description="The natural language response from the chatbot.")

class SQLExample(BaseModel):
    """Deep structure for code comparisons."""
    model_config = ConfigDict(extra="forbid")
    original_error: str = Field(..., description="The exact SQL query that failed.")
    fixed_sql: str = Field(..., description="The corrected, working SQL query.")

class LessonBody(BaseModel):
    """The core content of the Staff Engineer lesson."""
    model_config = ConfigDict(extra="forbid")
    instruction: str = Field(..., description="The single, actionable rule for future agents.")
    mistake: str = Field(..., description="A clear description of the specific error made.")
    reasoning: str = Field(..., description="Markdown Root Cause Analysis and Future Proofing.")
    example: SQLExample = Field(..., description="SQL Query Comparison example.")

class LessonDistillationOutput(BaseNodeOutput):
    """
    Structured output for the Lesson Distiller (Self-Healing).
    """
    is_global: bool = Field(..., description="True if the lesson applies to all queries, False if table-specific.")
    tags: List[str] = Field(..., description="Tags for the schema specific lessons.")
    title: str = Field(..., description="Short, descriptive title for the lesson.")
    body: LessonBody = Field(..., description="The core content of the lesson.")
    ending_note: str = Field(..., description="Professional sign-off (By following this instruction...)")

class SQLResponse(BaseModel):
    """
    Structured response from the LLM for SQL queries.
    """
    model_config = ConfigDict(extra="forbid")
    summary: str = Field(..., description="A natural language explanation or context-aware answer.")

class ExecuteSQLOutput(BaseModel):
    """
    Structured internal result for SQL execution (non-LLM).
    Used for local state, not LLM output.
    """
    status: str
    data: List[Dict[str, Any]] = Field(default_factory=list)
    row_count: int = 0
    is_aggregated: bool = False
    error_message: Optional[str] = None
